### ISSUE TITLE
goaldis doesn't work under Windows XP

### ISSUE THREAD

**Issue by RetingencyPlan** [rmitton/goaldis#2]
Not even with the pre-compiled .exe file or even the dumpall.bat file works on Windows XP at all. Any ideas to work around this?

**Comment by rmitton** [comment]
If you're using Visual Studio, make sure you select the older platform compiler toolchain that supports XP.
Or try compiling with gcc.
Otherwise no idea, I don't think there's anything that requires Vista in there.
