### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by mattboy9921** [rmitton/goaldis#5]
I can't seem to figure this one out. When running `dumpall.bat`, I get a repeated message that `MSVCR120D.dll` was not found. I've tried reinstalling the MS C++ 2013 redistributable for both x86 and x64, and tried this on 2 different systems. I can't figure out what else to try to get it working. Any help would be appreciated. Thanks!

**Comment by rmitton** [comment]
The ‘D’ at the end means it’s looking for the Debug version of those DLLs, not the regular version. You won’t get those from the redistributable I’m afraid, you need to install Visual Studio itself.

(You may also be able to find a copy of that DLL somewhere via Google or such)

**Comment by mattboy9921** [comment]
Thank you that worked. I installed VS 2013, previously had 2015 installed and wasn't working.
